services:
  database:
    container_name: postgres
    image: postgres:16.3-bookworm
    environment:
      - "POSTGRES_USER=${DOCKER_COMPOSE_POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${DOCKER_COMPOSE_POSTGRES_PASSWORD}"
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    container_name: app
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - "DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}"
      - "DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - main
    restart: always

networks:
  main:

volumes:
  postgres_data: